### ISSUE TITLE
Upgrade notice to users with older versions

### ISSUE THREAD

**Issue by EsteveSegura** [EsteveSegura/disposable-mail-api#13]
There are users who have outdated versions of the CLI, we must find a suitable way to notify them to update the package!

**Comment by AchrafAdev** [comment]
I will look to it tonight

**Comment by AchrafAdev** [comment]
Can I use another package to help us with this task or you prefer a native solution?

**Comment by EsteveSegura** [comment]
not perfect, but acceptable

**Comment by EsteveSegura** [comment]
Up to you, if you want @gtrabanco
